name: github-actions-demo

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Show deploy environment
        run: echo "Deploying to ${{ secrets.DEPLOY_ENV }}"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


